CREATE TABLE IF NOT EXISTS USERs (
	ID SERIAL PRIMARY KEY,
	EMAIL VARCHAR NOT NULL,
	PASSWORD VARCHAR NOT NULL
);


CREATE TABLE IF NOT EXISTS user_dob (
	ID SERIAL PRIMARY KEY,
	DOB DATE NOT NULL,
	USER_ID INTEGER NOT NULL REFERENCES USERS(ID) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS email_sent (
	sent_on TIMESTAMP NOT NULL
);

SELECT *
from user_dob WHERE
    DATE_PART('day', dob) = date_part('day', CURRENT_DATE + 1)
AND
    DATE_PART('month', dob) = date_part('month', CURRENT_DATE)

SELECT * FROM users u JOIN user_dob ud ON ud.user_id = u.id